# Generated by Django 5.2.5 on 2025-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userconfirm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfirm',
            options={'verbose_name': 'Tasdiqlash', 'verbose_name_plural': 'Tasdiqlashlar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('New', 'New'), ('Code verified', 'Code Verified'), ('Done', 'Done'), ('Finish', 'Finish')], default='New', max_length=13),
        ),
    ]
