# Generated by Django 5.2.5 on 2025-08-17 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_confirm', to=settings.AUTH_USER_MODEL),
        ),
    ]
