# Generated by Django 5.2.5 on 2025-08-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userconfirm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfirm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tasdiqlash', 'verbose_name_plural': 'Tasdiqlashlar'},
        ),
        migrations.RemoveField(
            model_name='userconfirm',
            name='is_confirmed',
        ),
    ]
